export default {
  primary: {
    _login_page_bg_1: '#3CAFA3',
    _login_page_bg_2: '#212934',

    _white: '#ffffff',
    _grey: '#2C3238',

    _disabled_textarea: '#E0E6EB',
    _disabled: '#CFD6DE',

    _normal: '#68768A',
    _normalBg: '#F8F9FA',

    _label: '#212934',
    _pending: '#F4CA64',
    _default: '#8895A7',
    _active: '#0EA0CE',
    _valid: '#3CAFA3',
    _error: '#B82020',

    _no_image_icon_color: '#fff',
    _no_image_bg_color: '#E7ECF0',

    _classic_input_color: '#000',
    _classic_input_bg_color: '#ffffff',
    _classic_input_color_disabled: '#CFD6DE',
    _classic_input_bg_color_disabled: '#F8F9FA',
    _classic_input_color_error: '#ffffff',
    _classic_input_bg_color_error: '#212934',
    _classic_input_border_color: '#8895A7',
    _classic_input_border_color_hover_active: '#0EA0CE',
    _classic_input_border_color_valid: '#3CAFA3',
    _classic_input_border_color_error: '#B82020',
    _classic_input_icon_color: '#8895A7',
    _classic_input_icon_color_hover_active: '#0EA0CE',
    _classic_input_icon_color_valid: '#3CAFA3',
    _classic_input_icon_color_error: '#B82020',
    _classic_input_label_color: '#212934',
    _classic_input_label_color_active: '#0EA0CE',
    _classic_input_label_color_valid: '#3CAFA3',
    _classic_input_label_color_error: '#B82020',

    _auth_btn_color: '#3CAFA3',
    _auth_btn_color_hover: '#212934',
    _auth_btn_bg_color: '#212934',
    _auth_btn_bg_color_hover: '#3CAFA3',
    _auth_btn_border_color: '#3CAFA3',
    _auth_btn_bg_color_pressed: '#349189',

    _client_btn_color: '#ffffff',
    _client_btn_color_hover: '#F4CA64',
    _client_btn_bg_color: '#F4CA64',
    _client_btn_bg_color_hover: '#ffffff',
    _client_btn_border_color: '#F4CA64',
    _client_btn_border_color_hover: '#F4CA64',
    _client_btn_bg_color_pressed: '#CFA562',
    _client_btn_bg_color_disabled: '#CFA562',

    _settings_btn_color: '#ffffff',
    _settings_btn_color_hover: '#212934',
    _settings_btn_bg_color: '#212934',
    _settings_btn_bg_color_hover: '#ffffff',
    _settings_btn_border_color: '#212934',
    _settings_btn_border_color_hover: '#212934',
    _settings_btn_bg_color_pressed: '#212934',
    _settings_btn_bg_color_disabled: '#212934',

    _balance_btn_color: '#ffffff',
    _balance_btn_color_hover: '#6ED7D3',
    _balance_btn_bg_color: '#6ED7D3',
    _balance_btn_bg_color_hover: '#ffffff',
    _balance_btn_border_color: '#6ED7D3',
    _balance_btn_border_color_hover: '#6ED7D3',
    _balance_btn_bg_color_pressed: '#56a6a2',
    _balance_btn_bg_color_disabled: '#56a6a2',

    _btn_color: '#ffffff',
    _btn_color_hover: '#3CAFA3',
    _btn_bg_color: '#3CAFA3',
    _btn_round_bg_color: '#2268A2',
    _btn_bg_color_hover: '#ffffff',
    _btn_border_color: '#3CAFA3',
    _btn_border_color_hover: '#3CAFA3',
    _btn_bg_color_pressed: '#349189',
    _btn_bg_color_disabled: '#349189',

    _btn_outlined_color: '#212934',
    _btn_outlined_active: '#FFFFFF',
    _btn_outlined_bg_color: '#FFFFFF',
    _btn_outlined_bg_color_active: '#212934',
    _btn_outlined_pressed: '#212934',

    _btn_outlined_color_disabled: '#8895A7',
    _btn_outlined_bg_color_disabled: '#E0E6EB',

    _btn_filled_color: '#FFFFFF',
    _btn_filled_color_active: '#B82020',
    _btn_filled_bg_color: '#E46464',
    _btn_filled_bg_color_active: '#FFFFFF',
    _btn_filled_border_color: '#E46464',
    _btn_filled_border_color_active: '#B82020',
    _btn_filled_pressed: '#E46464',

    _btn_filled_color_disabled: '#E0E6EB',
    _btn_filled_bg_color_disabled: '#B8C4CF',

    _icon_default: '#54607E',
    _icon_error: '#DC3030',
    _icon_bg_new_line: '#212934',
    _icon_bg_light_grey: '#E0E6EB',
    _icon_bg_grey: 'rgba(33,41,52,0.2)',
    _icon_bg_blue: 'rgba(14,160,206,0.2)',
    _icon_bg_yellow: 'rgba(244,202,100,0.2)',
    _icon_bg_green: 'rgba(60,175,163,0.2)',

    _driver_color: '#0EA0CE',
    _client_color: '#F4CA64',
    _payment_color: '#3CAFA3',
    _car_color: '#E46464',

    _tooltip_bg: '#fff',
    _tooltip_color: '#212934',

    _calendar_month_arrow: '#fff',
    _calendar_month_arrow_hover: '#3CAFA3',
    _calendar_year_arrow: '#3CAFA3',
    _calendar_year_arrow_hover: '#212934',
    _calendar_input_border_color: '#212934',
    _calendar_input_color: '#212934',
    _calendar_bg: '#fff',
    _calendar_header_border_top: '#3CAFA3',
    _calendar_header_bg: '#212934',
    _calendar_header_color: '#fff',
    _calendar_month_hover_color: '#3CAFA3',
    _calendar_days_color: '#5F6B7A',
    _calendar_current_month_day_color: '#161C23',
    _calendar_not_current_month_day_color: '#E0E6EB',
    _calendar_current_month_day_bg: '#fff',
    _calendar_day_wrap_border: '#3CAFA3',
    _calendar_day_wrap_color: '#3CAFA3',
    _calendar_month_year_splitter_border_bottom: '#E0E6EB',
    _calendar_month_year_item_border: '#2A9187',
    _calendar_month_year_item_color: '#2A9187',

    _404_border_color: '#DC3030',
    _404_icon_bg: 'rgba(220,48,48,0.2)',
    _404_icon_color: '#DC3030',
    _404_text_color: '#212934',
    _404_link_color: '#0EA0CE',

    _header_bg: '#212A34',
    _header_line: '#2A9187',
    _footer_bg: '#161C23',
    _title_color: '#2A9187',
    _link_choose: '#0EA0CE',
    _order_content_bg: '#EFF2F5',
    _icon_distance_bg: 'rgba(180,108,241,0.2)',
    _icon_price_bg: 'rgba(60,175,163,0.2)',
    _icon_time_bg: 'rgba(244,202,100,0.3)',

    _icon_border_green: '#2A9187',
    _icon_border_violet: '#B46CF1',

    _submit_btn_color: '#ffffff',
    _submit_btn_color_hover: '#2A9187',
    _submit_btn_bg_color: '#2A9187',
    _submit_btn_bg_color_hover: '#ffffff',
    _submit_btn_border_color: '#2A9187',
    _submit_btn_border_color_hover: '#2A9187',
    _submit_btn_bg_color_pressed: '#24776d',
    _submit_btn_bg_color_disabled: '#24776d',

    _car_found_color: '#2A9187',
    _car_not_found_color: '#E46464',
    _car_type_border_color: '#E0E6EB',

    _label_color: '#7D8494',
    _text_color_blue: '#6ED7D3',
    _text_color_yellow: '#F4CA64',

    _stepper_line_color: 'rgba(224, 230, 235, 0.4)',
    _stepper_point_color: 'rgba(224, 230, 235, 1)',

    _input_email_bg: 'rgba(184, 196, 207, 0.1)'
  },
  secondary: {
    _default: '#ECECEE',
    _errorBg: '#212934',
  }
};
